- name: "meta: automated"
  color: "d73a4a"
  description: "Automatic Pull Request"
- name: "meta: automerge"
  color: "0075ca"
  description: "Automerge this PR"

- name: "type: dependencies"
  color: "d73a4a"
  description: "Dependency update"
- name: "type: sync"
  color: "d73a4a"
  description: "File cross-repo syncing"
- name: "type: fix"
  color: "0075ca"
  description: "Fixes a bug"
- name: "type: feat"
  color: "0075ca"
  description: "Adds a feature"
- name: "type: refactor"
  color: "0075ca"
  description: "Refactor code without API change"

- name: "semver: major"
  color: "fb6a65"
- name: "semver: minor"
  color: "fb9265"
- name: "semver: patch"
  color: "fccb97"
