name: Test

on: 
  push:
  workflow_call:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and lint
      run: |
        yarn install
        yarn test
      env:
        CI: true
