name: Test

on: 
  push:
  workflow_call:
    secrets:
      SSH_GITHUB_KEY:
        required: false

# Add PUBLIC_KEY to account ssh keys
# Add PRIVATE_KEY to CI as SSH_GITHUB_KEY

jobs:
  lint-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        continue-on-error: true
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_GITHUB_KEY }}
      - name: yarn install and lint
        run: |
          yarn install
          yarn test
        env:
          CI: true
